import logger from '../config/logger.js';

/**
 * Generate a CloudFormation template from architecture nodes and edges
 * Maps AWS service nodes to CloudFormation resource definitions
 * @param {Array} nodes - Architecture nodes
 * @param {Array} edges - Architecture edges
 * @param {string} architectureName - Name of the architecture
 * @param {string} region - AWS region (optional, for region-specific defaults)
 */
export const generateCloudFormationTemplate = (nodes, edges, architectureName, region = 'us-east-1') => {
  const resources = {};
  const outputs = {};
  const parameters = {};
  const mappings = {};
  const nodeMap = {}; // Track node IDs to resource logical IDs

  // Find VPC node to get region (VPC is the source of truth for region)
  const vpcNode = nodes.find(node => node.data?.serviceType === 'vpc');
  const deploymentRegion = vpcNode?.data?.region || region;

  // Add default parameters for sensitive data
  parameters.DBPassword = {
    Type: 'String',
    NoEcho: true,
    Description: 'Database master password',
    MinLength: 8,
    Default: 'ChangeMe123!',
  };

  // Add region parameter
  parameters.AWSRegion = {
    Type: 'String',
    Default: deploymentRegion,
    Description: 'AWS region for deployment',
  };

  // Process VPC and infrastructure nodes first (they need to exist before other resources)
  const infrastructureNodes = nodes.filter(node => 
    ['vpc', 'subnet_public', 'subnet_private', 'security_group'].includes(node.data?.serviceType)
  );
  const serviceNodes = nodes.filter(node => 
    !['vpc', 'subnet_public', 'subnet_private', 'security_group'].includes(node.data?.serviceType)
  );

  // Process infrastructure nodes first (VPC, subnets, security groups)
  infrastructureNodes.forEach((node) => {
    const { data } = node;
    const serviceType = data.serviceType;
    const logicalId = sanitizeLogicalId(`${serviceType}${node.id.replace('node_', '')}`);
    nodeMap[node.id] = logicalId;

    try {
      const generator = serviceGenerators[serviceType];
      if (generator) {
        resources[logicalId] = generator(data, logicalId, nodeMap, deploymentRegion);
      } else {
        logger.warn(`No generator for service type: ${serviceType}, skipping`);
      }
    } catch (error) {
      logger.error(`Error generating resource for ${serviceType}:`, error);
    }
  });

  // Get VPC and Security Group references for service nodes
  const vpcLogicalId = vpcNode ? nodeMap[vpcNode.id] : null;
  const securityGroupNode = nodes.find(node => node.data?.serviceType === 'security_group');
  const securityGroupLogicalId = securityGroupNode ? nodeMap[securityGroupNode.id] : null;

  // Process service nodes (they can reference VPC/security groups)
  serviceNodes.forEach((node) => {
    const { data } = node;
    const serviceType = data.serviceType;
    const logicalId = sanitizeLogicalId(`${serviceType}${node.id.replace('node_', '')}`);
    nodeMap[node.id] = logicalId;

    try {
      const generator = serviceGenerators[serviceType];
      if (generator) {
        // Pass VPC and security group context to service generators
        const context = {
          vpcId: vpcLogicalId ? { Ref: vpcLogicalId } : undefined,
          securityGroupId: securityGroupLogicalId ? { 'Fn::GetAtt': [securityGroupLogicalId, 'GroupId'] } : undefined,
        };
        resources[logicalId] = generator(data, logicalId, nodeMap, deploymentRegion, context);
      } else {
        logger.warn(`No generator for service type: ${serviceType}, skipping`);
      }
    } catch (error) {
      logger.error(`Error generating resource for ${serviceType}:`, error);
    }
  });

  // Add Lambda execution role if Lambda functions exist
  const hasLambda = nodes.some(node => node.data.serviceType === 'lambda');
  if (hasLambda && !resources.LambdaExecutionRole) {
    resources.LambdaExecutionRole = {
      Type: 'AWS::IAM::Role',
      Properties: {
        AssumeRolePolicyDocument: {
          Version: '2012-10-17',
          Statement: [{
            Effect: 'Allow',
            Principal: { Service: 'lambda.amazonaws.com' },
            Action: 'sts:AssumeRole',
          }],
        },
        ManagedPolicyArns: [
          'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
        ],
      },
    };
  }

  // Generate outputs for key resources
  Object.entries(resources).forEach(([logicalId, resource]) => {
    generateOutputsForResource(logicalId, resource, outputs);
  });

  const template = {
    AWSTemplateFormatVersion: '2010-09-09',
    Description: `CloudFormation template for ${architectureName}. Generated by CloudCanvas-Architect.`,
    Parameters: Object.keys(parameters).length > 0 ? parameters : undefined,
    Mappings: Object.keys(mappings).length > 0 ? mappings : undefined,
    Resources: resources,
    Outputs: Object.keys(outputs).length > 0 ? outputs : undefined,
  };

  // Remove undefined properties
  Object.keys(template).forEach(key => {
    if (template[key] === undefined) delete template[key];
  });

  return template;
};

// Helper function to sanitize logical IDs
const sanitizeLogicalId = (id) => {
  return id.replace(/[^a-zA-Z0-9]/g, '').replace(/^[0-9]/, 'R$&');
};

// Default Amazon Linux 2 AMI IDs by region (as fallback if SSM doesn't work)
// These are approximate and may need updating - SSM Parameter Store is preferred
const DEFAULT_AL2_AMIS = {
  'us-east-1': 'ami-0c55b159cbfafe1f0',      // N. Virginia
  'us-east-2': 'ami-0c55b159cbfafe1f0',      // Ohio (approximate)
  'us-west-1': 'ami-0c55b159cbfafe1f0',      // N. California (approximate)
  'us-west-2': 'ami-0c55b159cbfafe1f0',      // Oregon (approximate)
  'eu-west-1': 'ami-0c55b159cbfafe1f0',      // Ireland (approximate)
  'eu-central-1': 'ami-0c55b159cbfafe1f0',   // Frankfurt (approximate)
  'ap-south-1': 'ami-0c55b159cbfafe1f0',    // Mumbai (approximate)
  'ap-southeast-1': 'ami-0c55b159cbfafe1f0', // Singapore (approximate)
  'ap-northeast-1': 'ami-0c55b159cbfafe1f0', // Tokyo (approximate)
};

/**
 * Get default AMI ID for EC2 instance
 * Prefers SSM Parameter Store (region-aware, always up-to-date)
 * Falls back to hardcoded AMI if SSM not available
 */
const getDefaultAMI = (region, customAmiId) => {
  if (customAmiId) {
    return customAmiId;
  }
  
  // Use SSM Parameter Store to get latest Amazon Linux 2 AMI
  // This is the AWS-recommended approach and automatically gets the correct AMI for the region
  return {
    'Fn::Sub': '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
  };
};

// Helper function to generate outputs
const generateOutputsForResource = (logicalId, resource, outputs) => {
  const outputGenerators = {
    'AWS::EC2::Instance': () => {
      outputs[`${logicalId}PublicIP`] = {
        Description: `Public IP address of ${logicalId}`,
        Value: { 'Fn::GetAtt': [logicalId, 'PublicIp'] },
        Export: { Name: { 'Fn::Sub': `\${AWS::StackName}-${logicalId}-PublicIP` } },
      };
    },
    'AWS::RDS::DBInstance': () => {
      outputs[`${logicalId}Endpoint`] = {
        Description: `Database endpoint for ${logicalId}`,
        Value: { 'Fn::GetAtt': [logicalId, 'Endpoint.Address'] },
        Export: { Name: { 'Fn::Sub': `\${AWS::StackName}-${logicalId}-Endpoint` } },
      };
    },
    'AWS::S3::Bucket': () => {
      outputs[`${logicalId}Name`] = {
        Description: `S3 bucket name for ${logicalId}`,
        Value: { Ref: logicalId },
        Export: { Name: { 'Fn::Sub': `\${AWS::StackName}-${logicalId}-Name` } },
      };
    },
    'AWS::Lambda::Function': () => {
      outputs[`${logicalId}Arn`] = {
        Description: `ARN of Lambda function ${logicalId}`,
        Value: { 'Fn::GetAtt': [logicalId, 'Arn'] },
        Export: { Name: { 'Fn::Sub': `\${AWS::StackName}-${logicalId}-Arn` } },
      };
    },
    'AWS::ElasticLoadBalancingV2::LoadBalancer': () => {
      outputs[`${logicalId}DNS`] = {
        Description: `DNS name of ${logicalId}`,
        Value: { 'Fn::GetAtt': [logicalId, 'DNSName'] },
        Export: { Name: { 'Fn::Sub': `\${AWS::StackName}-${logicalId}-DNS` } },
      };
    },
    'AWS::DynamoDB::Table': () => {
      outputs[`${logicalId}Name`] = {
        Description: `DynamoDB table name for ${logicalId}`,
        Value: { Ref: logicalId },
        Export: { Name: { 'Fn::Sub': `\${AWS::StackName}-${logicalId}-Name` } },
      };
    },
  };

  const generator = outputGenerators[resource.Type];
  if (generator) {
    generator();
  }
};

// Service generators mapped by service type
const serviceGenerators = {
  // EC2 instance with VPC/security group support
  ec2: (data, logicalId, nodeMap, region, context = {}) => {
    // Get AMI ID - uses SSM Parameter Store for latest Amazon Linux 2 (region-aware)
    const imageId = getDefaultAMI(region, data.config?.amiId);

    // Use context security group if available, otherwise fall back to config
    const securityGroupIds = data.config?.securityGroups || 
      (context.securityGroupId ? [context.securityGroupId] : undefined);

    return {
      Type: 'AWS::EC2::Instance',
      Properties: {
        ImageId: imageId,
        InstanceType: data.config?.instanceType || 't2.micro',
        SecurityGroupIds: securityGroupIds,
        SubnetId: data.config?.subnetId || undefined,
        KeyName: data.config?.keyName || undefined,
        IamInstanceProfile: data.config?.instanceProfile || undefined,
        UserData: data.config?.userData ? { 'Fn::Base64': data.config.userData } : undefined,
        Tags: [
          {
            Key: 'Name',
            Value: data.label || logicalId,
          },
          {
            Key: 'ManagedBy',
            Value: 'CloudCanvas-Architect',
          },
        ],
      },
    };
  },

  rds: (data, logicalId, nodeMap, region, context = {}) => {
    // Use context security group if available
    const vpcSecurityGroups = data.config?.securityGroups || 
      (context.securityGroupId ? [context.securityGroupId] : undefined);

    return {
      Type: 'AWS::RDS::DBInstance',
      Properties: {
        DBInstanceIdentifier: logicalId.toLowerCase().substring(0, 63),
        Engine: data.config?.engine || 'mysql',
        EngineVersion: data.config?.engineVersion || '8.0.35',
        DBInstanceClass: data.config?.dbInstanceClass || 'db.t3.micro',
        MasterUsername: data.config?.masterUsername || 'admin',
        MasterUserPassword: { Ref: 'DBPassword' }, // From parameters
        AllocatedStorage: String(data.config?.allocatedStorage || '20'),
        StorageType: data.config?.storageType || 'gp3',
        StorageEncrypted: data.config?.encrypted !== false,
        MultiAZ: data.config?.multiAZ || false,
        PubliclyAccessible: data.config?.publiclyAccessible || false,
        BackupRetentionPeriod: data.config?.backupRetention || 7,
        VPCSecurityGroups: vpcSecurityGroups,
        DBSubnetGroupName: data.config?.dbSubnetGroup || undefined,
        Tags: [
          {
            Key: 'Name',
            Value: data.label || logicalId,
          },
        ],
      },
    };
  },

  alb: (data, logicalId, nodeMap, region, context = {}) => {
    // Use context security group if available
    const securityGroups = data.config?.securityGroups || 
      (context.securityGroupId ? [context.securityGroupId] : undefined);

    return {
      Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
      Properties: {
        Name: logicalId.toLowerCase().substring(0, 32),
        Type: 'application',
        Scheme: data.config?.scheme || 'internet-facing',
        IpAddressType: 'ipv4',
        SecurityGroups: securityGroups,
        Subnets: data.config?.subnets || undefined,
        Tags: [
          {
            Key: 'Name',
            Value: data.label || logicalId,
          },
        ],
      },
    };
  },

  lambda: (data, logicalId) => ({
    Type: 'AWS::Lambda::Function',
    Properties: {
      FunctionName: logicalId,
      Runtime: data.config?.runtime || 'nodejs20.x',
      Handler: data.config?.handler || 'index.handler',
      Role: {
        'Fn::GetAtt': ['LambdaExecutionRole', 'Arn'],
      },
      Code: {
        ZipFile: data.config?.code || 'exports.handler = async (event) => { return { statusCode: 200, body: JSON.stringify("Hello from Lambda!") }; };',
      },
      Timeout: data.config?.timeout || 30,
      MemorySize: data.config?.memorySize || 128,
      Environment: data.config?.environment ? {
        Variables: data.config.environment,
      } : undefined,
      Tags: [
        {
          Key: 'Name',
          Value: data.label || logicalId,
        },
      ],
    },
  }),

  s3: (data, logicalId) => ({
    Type: 'AWS::S3::Bucket',
    Properties: {
      BucketName: data.config?.bucketName ? `${data.config.bucketName}-${Date.now()}`.substring(0, 63) : undefined,
      VersioningConfiguration: {
        Status: data.config?.versioning ? 'Enabled' : 'Suspended',
      },
      BucketEncryption: {
        ServerSideEncryptionConfiguration: [{
          ServerSideEncryptionByDefault: {
            SSEAlgorithm: 'AES256',
          },
        }],
      },
      PublicAccessBlockConfiguration: {
        BlockPublicAcls: data.config?.blockPublicAccess !== false,
        BlockPublicPolicy: data.config?.blockPublicAccess !== false,
        IgnorePublicAcls: data.config?.blockPublicAccess !== false,
        RestrictPublicBuckets: data.config?.blockPublicAccess !== false,
      },
      Tags: [
        {
          Key: 'Name',
          Value: data.label || logicalId,
        },
      ],
    },
  }),

  dynamodb: (data, logicalId) => ({
    Type: 'AWS::DynamoDB::Table',
    Properties: {
      TableName: logicalId,
      BillingMode: data.config?.billingMode || 'PAY_PER_REQUEST',
      AttributeDefinitions: data.config?.attributes || [
        {
          AttributeName: 'id',
          AttributeType: 'S',
        },
      ],
      KeySchema: data.config?.keySchema || [
        {
          AttributeName: 'id',
          KeyType: 'HASH',
        },
      ],
      PointInTimeRecoverySpecification: {
        PointInTimeRecoveryEnabled: data.config?.pointInTimeRecovery || false,
      },
      Tags: [
        {
          Key: 'Name',
          Value: data.label || logicalId,
        },
      ],
    },
  }),

  vpc: (data, logicalId) => ({
    Type: 'AWS::EC2::VPC',
    Properties: {
      CidrBlock: data.config?.cidrBlock || '10.0.0.0/16',
      EnableDnsHostnames: true,
      EnableDnsSupport: true,
      Tags: [
        {
          Key: 'Name',
          Value: data.label || data.config?.name || logicalId,
        },
      ],
    },
  }),

  // Security Group resource
  security_group: (data, logicalId, nodeMap) => {
    // Find VPC reference
    const vpcEntry = Object.entries(nodeMap).find(([nodeId, lid]) => lid.startsWith('vpc'));
    const vpcRef = vpcEntry ? { Ref: vpcEntry[1] } : undefined;

    return {
      Type: 'AWS::EC2::SecurityGroup',
      Properties: {
        GroupDescription: data.config?.description || `Security group for ${data.label || logicalId}`,
        GroupName: data.config?.name || logicalId,
        VpcId: vpcRef,
        SecurityGroupIngress: [
          // Allow SSH
          {
            IpProtocol: 'tcp',
            FromPort: 22,
            ToPort: 22,
            CidrIp: '0.0.0.0/0',
            Description: 'SSH access',
          },
          // Allow HTTP
          {
            IpProtocol: 'tcp',
            FromPort: 80,
            ToPort: 80,
            CidrIp: '0.0.0.0/0',
            Description: 'HTTP access',
          },
          // Allow HTTPS
          {
            IpProtocol: 'tcp',
            FromPort: 443,
            ToPort: 443,
            CidrIp: '0.0.0.0/0',
            Description: 'HTTPS access',
          },
        ],
        SecurityGroupEgress: [
          {
            IpProtocol: '-1',
            CidrIp: '0.0.0.0/0',
            Description: 'Allow all outbound traffic',
          },
        ],
        Tags: [
          {
            Key: 'Name',
            Value: data.label || data.config?.name || logicalId,
          },
        ],
      },
    };
  },

  // Public Subnet
  subnet_public: (data, logicalId, nodeMap) => {
    // Find VPC reference
    const vpcEntry = Object.entries(nodeMap).find(([nodeId, lid]) => lid.startsWith('vpc'));
    const vpcRef = vpcEntry ? { Ref: vpcEntry[1] } : undefined;

    return {
      Type: 'AWS::EC2::Subnet',
      Properties: {
        VpcId: vpcRef,
        CidrBlock: data.config?.cidrBlock || '10.0.1.0/24',
        AvailabilityZone: data.config?.availabilityZone || { 'Fn::Select': [0, { 'Fn::GetAZs': '' }] },
        MapPublicIpOnLaunch: true,
        Tags: [
          {
            Key: 'Name',
            Value: data.label || data.config?.name || `${logicalId}-public`,
          },
        ],
      },
    };
  },

  // Private Subnet
  subnet_private: (data, logicalId, nodeMap) => {
    // Find VPC reference
    const vpcEntry = Object.entries(nodeMap).find(([nodeId, lid]) => lid.startsWith('vpc'));
    const vpcRef = vpcEntry ? { Ref: vpcEntry[1] } : undefined;

    return {
      Type: 'AWS::EC2::Subnet',
      Properties: {
        VpcId: vpcRef,
        CidrBlock: data.config?.cidrBlock || '10.0.2.0/24',
        AvailabilityZone: data.config?.availabilityZone || { 'Fn::Select': [1, { 'Fn::GetAZs': '' }] },
        MapPublicIpOnLaunch: false,
        Tags: [
          {
            Key: 'Name',
            Value: data.label || data.config?.name || `${logicalId}-private`,
          },
        ],
      },
    };
  },

  // Additional services
  sqs: (data, logicalId) => ({
    Type: 'AWS::SQS::Queue',
    Properties: {
      QueueName: logicalId,
      VisibilityTimeout: data.config?.visibilityTimeout || 30,
      MessageRetentionPeriod: data.config?.messageRetention || 345600,
      ReceiveMessageWaitTimeSeconds: data.config?.receiveWaitTime || 0,
      Tags: [
        {
          Key: 'Name',
          Value: data.label || logicalId,
        },
      ],
    },
  }),

  sns: (data, logicalId) => ({
    Type: 'AWS::SNS::Topic',
    Properties: {
      TopicName: logicalId,
      DisplayName: data.label || logicalId,
      Tags: [
        {
          Key: 'Name',
          Value: data.label || logicalId,
        },
      ],
    },
  }),

  ecs: (data, logicalId) => ({
    Type: 'AWS::ECS::Cluster',
    Properties: {
      ClusterName: logicalId,
      CapacityProviders: ['FARGATE', 'FARGATE_SPOT'],
      Tags: [
        {
          Key: 'Name',
          Value: data.label || logicalId,
        },
      ],
    },
  }),

  eks: (data, logicalId) => ({
    Type: 'AWS::EKS::Cluster',
    Properties: {
      Name: logicalId,
      Version: data.config?.version || '1.28',
      RoleArn: data.config?.roleArn || { Ref: 'AWS::NoValue' },
      ResourcesVpcConfig: {
        SubnetIds: data.config?.subnets || [],
      },
      Tags: [
        {
          Key: 'Name',
          Value: data.label || logicalId,
        },
      ],
    },
  }),

  apigateway: (data, logicalId) => ({
    Type: 'AWS::ApiGatewayV2::Api',
    Properties: {
      Name: logicalId,
      ProtocolType: data.config?.protocol || 'HTTP',
      Tags: {
        Name: data.label || logicalId,
      },
    },
  }),

  cloudfront: (data, logicalId) => {
    // CloudFront requires at least one origin - provide default if none configured
    const origins = data.config?.origins && data.config.origins.length > 0
      ? data.config.origins
      : [
          {
            Id: `${logicalId}Origin`,
            DomainName: data.config?.domainName || `${logicalId.toLowerCase()}.s3.amazonaws.com`,
            S3OriginConfig: data.config?.isS3Origin !== false ? {} : undefined,
            CustomOriginConfig: data.config?.isS3Origin === false ? {
              OriginProtocolPolicy: 'https-only',
              OriginSSLProtocols: ['TLSv1.2'],
            } : undefined,
          }
        ];

    return {
      Type: 'AWS::CloudFront::Distribution',
      Properties: {
        DistributionConfig: {
          Enabled: true,
          DefaultCacheBehavior: {
            TargetOriginId: `${logicalId}Origin`,
            ViewerProtocolPolicy: 'redirect-to-https',
            AllowedMethods: ['GET', 'HEAD', 'OPTIONS'],
            CachedMethods: ['GET', 'HEAD'],
            ForwardedValues: {
              QueryString: false,
              Cookies: { Forward: 'none' },
            },
          },
          Origins: origins,
        },
      },
    };
  },

  elasticache: (data, logicalId) => ({
    Type: 'AWS::ElastiCache::CacheCluster',
    Properties: {
      ClusterName: logicalId.toLowerCase(),
      Engine: data.config?.engine || 'redis',
      CacheNodeType: data.config?.nodeType || 'cache.t3.micro',
      NumCacheNodes: data.config?.numNodes || 1,
      Tags: [
        {
          Key: 'Name',
          Value: data.label || logicalId,
        },
      ],
    },
  }),
};
